apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: dev-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: html-cache
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-cache
        emptyDir: {}
