apiVersion: v1
kind: Namespace
metadata:
  name: dev-apps
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-apps-quota
  namespace: dev-apps
spec:
  hard:
    pods: "5"
    requests.cpu: "500m"
    limits.cpu: "1"
    requests.memory: "512Mi"
    limits.memory: "1Gi"
